[workspace]
resolver = "3"
members = [
  "crates/domain",
  "crates/ports",
  "crates/application",
  "crates/infra",
  "crates/gnative_core",
  "crates/gnative_protocol",
  "crates/gnative_ui",
  "crates/gnative_widgets",
  "crates/gnative_sdk",
  "crates/gnative_demo",
  "app",
]

[workspace.package]
version    = "0.0.1"
edition    = "2024"
license    = "MIT"
repository = "https://github.com/zooeywm/germinal"
authors    = ["zooeywm <zooeywm@gmail.com>"]

[workspace.dependencies]
germinal-domain                  = { path = "crates/domain" }
germinal-ports                   = { path = "crates/ports" }
germinal-application             = { path = "crates/application" }
germinal-infra                   = { path = "crates/infra" }
germinal-gnative-core            = { path = "crates/gnative_core" }
germinal-gnative-protocol        = { path = "crates/gnative_protocol" }
germinal-gnative-ui              = { path = "crates/gnative_ui" }
germinal-gnative-widgets         = { path = "crates/gnative_widgets" }
germinal-gnative-sdk             = { path = "crates/gnative_sdk" }

# util
smol_str      = "0.2"
unicode-width = "0.2"
serde         = { version = "1", features = ["derive"] }
serde_json    = "1"

# application
kudi = "0.1"

# infra
alacritty_terminal = "0.26"
wgpu               = "29.0"
crossfont          = "0.9"
winit              = "0.30"
pollster           = "0.4"
portable-pty       = "0.9"
rusqlite           = { version = "0.31", features = ["bundled"] }
nix                = { version = "0.31", default-features = false }
compio             = { version = "0.19", default-features = false }
rayon              = "1"

[profile.product]
inherits      = "release"
opt-level     = 3
debug         = false
strip         = "none"
lto           = true
codegen-units = 1
incremental   = false
panic         = "abort"
