[workspace]
resolver = "3"
members = [
  "crates/domain",
  "crates/ports",
  "crates/application",
  "crates/infra",
  "crates/gnative_core",
  "crates/gnative_protocol",
  "crates/gnative_ui",
  "crates/gnative_widgets",
  "crates/gnative_sdk",
  "crates/gnative_demo",
  "app",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/cradiy/germinal"

[workspace.dependencies]
germinal-domain = { path = "crates/domain" }
germinal-ports = { path = "crates/ports" }
germinal-application = { path = "crates/application" }
germinal-infra = { path = "crates/infra" }
germinal-gnative-core = { path = "crates/gnative_core" }
germinal-gnative-protocol = { path = "crates/gnative_protocol" }
germinal-gnative-ui = { path = "crates/gnative_ui" }
germinal-gnative-widgets = { path = "crates/gnative_widgets" }
germinal-gnative-sdk = { path = "crates/gnative_sdk" }

# util
clap = { version = "4", features = ["derive"] }
unicode-width = "0.2"
unicode-normalization = "0.1"
unicode-segmentation = "1"
cosmic-text = "0.14.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
eros = "0.6"
tracing = "0.1"
tracing-subscriber = "0.3"
toml = "1.1"
base64 = "0.22"
flate2 = "1"
png = "0.18"

# application
kudi = "0.1"

# infra
alacritty_terminal = "0.26"
wgpu = { version = "30.0", default-features = false, features = [
  "dx12",
  "metal",
  "parking_lot",
  "std",
  "vulkan",
  "webgpu",
  "wgsl",
] }
crossfont = "0.9"
winit = "0.30"
pollster = "0.4"
portable-pty = "0.9"
nix = { version = "0.31", default-features = false }
compio = { version = "0.19", default-features = false }
rayon = "1"
ash = "0.38"
gstreamer = { version = "0.25.3", features = ["v1_28"] }
gstreamer-app = { version = "0.25.2", features = ["v1_28"] }
gstreamer-video = { version = "0.25.3", features = ["v1_28"] }
gstreamer-allocators = { version = "0.25.2", features = ["v1_28"] }
arboard = { version = "3", features = ["wayland-data-control"] }
notify-rust = "4"
memmap2 = "0.9"

[profile.product]
inherits = "release"
opt-level = 3
debug = false
strip = "none"
lto = true
codegen-units = 1
incremental = false
panic = "abort"
