[package]
name = "germinal"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
germinal-application.workspace = true
germinal-domain.workspace = true
germinal-infra.workspace = true
germinal-gnative-protocol.workspace = true
germinal-ports.workspace = true
winit.workspace = true
arboard.workspace = true
serde.workspace = true
thiserror.workspace = true
eros.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
toml.workspace = true

[dev-dependencies]
base64.workspace = true
png.workspace = true
unicode-width.workspace = true
wgpu.workspace = true
